### ISSUE TITLE
Getting Banned error

### ISSUE THREAD

**Issue by divyanshunegi** [elias94/pyomegle#4]
Whenever I try the sample code it throws this error in the console.
just after omegle.start()
`Unhandled event: [u'error', u'You are temporarily banned.']`

**Comment by LucaBastelt** [comment]
Yeah same problem here. Using the sample code and the pip version of the library

// EDIT
Using the code directly from the repo works, is the pip version up to date? The versions seem to match.

// EDIT 2
Well now it works with the pip version as well. Weird

//EDIT 3
And now its broken again, no clue what the pattern is here

//EDIT 4
Got it, it works after I solved the recaptcha on omegle. I guess the behavior could be changed to represent that because "You are banned" is not correct.

**Comment by divyanshunegi** [comment]
Yes the issue is related to recaptcha, the way omegle handle recaptcha is changed, so this library need to be updated, I made it work by tinkering with the code, but will update and will do a pull request as soon I get some time
